/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_eddy_testndk_TestNDK */

#ifndef _Included_com_eddy_testndk_TestNDK
#define _Included_com_eddy_testndk_TestNDK
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_eddy_testndk_TestNDK
 * Method:    stringTestNdk
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_eddy_testndk_TestNDK_stringTestNdk
  (JNIEnv *, jobject);

/*
 * Class:     com_eddy_testndk_TestNDK
 * Method:    add
 * Signature: (II)I
 */
JNIEXPORT jint JNICALL Java_com_eddy_testndk_TestNDK_add
  (JNIEnv *, jobject, jint, jint);

#ifdef __cplusplus
}
#endif
#endif
